public enum CustomerValidationError
{
    EmptyName,
    NameTooLong,
    DuplicateName,
    EmptyNIP,
    DuplicateNIP,
    InvalidNIP,
    NotDigitsNIP,
    EmptyZipCode,
    InvalidZipCode,
    NotDigitsZipCode,
    EmptyCity,
    CityTooLong,
    InvalidEmail,
    EmptyEmail,
    EmailTooLong,
    DuplicateEmail,
    EmptyStreet,
    StreetTooLong
}
